### ISSUE TITLE
Error on boot.

### ISSUE THREAD

**Issue by MAPReiff** [andrejsavikin/DiscordLink#1]
Hello,
So I just tried configuring the bot, and upon the first boot, I get this error [http://pastebin.com/usYhkDJL](http://pastebin.com/usYhkDJL)
I have installed the proper dependencies, as well as configured the config.json.

Any Ideas?

**Comment by ThatSava** [comment]
Seems like an error in twitch configuration somewhere. Can you try disabling the twitch integration and running it to see if the error is still there?
Edit: Sorry for late response. Gmail decided to filter the email into spam for some reason

**Comment by ThatSava** [comment]
Will be reopened if I get more info
